name: flutter_simple_firebase_auth
description: A new Flutter project made with GetX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.7.0
  firebase_auth: ^3.1.2
  firebase_storage: ^10.0.4
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.1.1

  get: ^4.3.8
  equatable: ^2.0.3
  page_indicator: ^0.4.1

  flutter_facebook_auth: ^3.5.2
  flutter_hooks: ^0.18.0
  image_picker: ^0.8.4+2
  cached_network_image: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
